// =============================================
// Fallback course data for when backend is unavailable
// =============================================

export const fallbackCourses = [
  {
    id: '1', slug: 'complete-nextjs-15-bootcamp',
    title: 'The Complete Next.js 15 Bootcamp',
    short_description: 'Build modern full-stack apps with Next.js 15, React 19, and TypeScript',
    description: 'Master Next.js 15 from scratch. Learn Server Components, App Router, Server Actions, authentication, database integration, deployment and more.',
    price: 2499.00, discount_price: 499.00,
    author: 'Sai Srinivas Padala',
    category_name: 'Web Development', category_slug: 'web-development',
    difficulty: 'intermediate', duration_hours: 42.5, lessons_count: 385,
    rating: 4.85, reviews_count: 12840, students_count: 54200,
    is_featured: true, is_bestseller: true,
    tags: ['nextjs', 'react', 'typescript', 'fullstack'],
  },
  {
    id: '2', slug: 'python-data-science-ml',
    title: 'Python for Data Science & ML',
    short_description: 'Master Python for data analysis, visualization, and machine learning',
    description: 'Comprehensive Python course covering NumPy, Pandas, Matplotlib, Scikit-learn, TensorFlow, and real-world data science projects.',
    price: 1999.00, discount_price: 399.00,
    author: 'Priya Sharma',
    category_name: 'Data Science', category_slug: 'data-science',
    difficulty: 'beginner', duration_hours: 56.0, lessons_count: 420,
    rating: 4.78, reviews_count: 9650, students_count: 41500,
    is_featured: true, is_bestseller: true,
    tags: ['python', 'ml', 'data-science', 'tensorflow'],
  },
  {
    id: '3', slug: 'react-native-build-10-apps',
    title: 'React Native - Build 10 Apps',
    short_description: 'Create cross-platform mobile apps with React Native and Expo',
    description: 'Learn React Native by building 10 production-ready mobile applications.',
    price: 1799.00, discount_price: 349.00,
    author: 'Rahul Verma',
    category_name: 'Mobile Development', category_slug: 'mobile-development',
    difficulty: 'intermediate', duration_hours: 38.0, lessons_count: 310,
    rating: 4.72, reviews_count: 7200, students_count: 28900,
    is_featured: true, is_bestseller: false,
    tags: ['react-native', 'mobile', 'expo', 'javascript'],
  },
  {
    id: '4', slug: 'aws-solutions-architect-pro',
    title: 'AWS Solutions Architect Pro',
    short_description: 'Master AWS cloud architecture and pass the SAP-C02 certification',
    description: 'Prepare for the AWS Solutions Architect Professional certification.',
    price: 2999.00, discount_price: 599.00,
    author: 'Anil Kumar',
    category_name: 'Cloud & DevOps', category_slug: 'cloud-devops',
    difficulty: 'advanced', duration_hours: 48.0, lessons_count: 390,
    rating: 4.90, reviews_count: 5800, students_count: 22400,
    is_featured: true, is_bestseller: true,
    tags: ['aws', 'cloud', 'certification', 'devops'],
  },
  {
    id: '5', slug: 'ethical-hacking-penetration-testing',
    title: 'Ethical Hacking & Penetration Testing',
    short_description: 'Become a certified ethical hacker with hands-on security labs',
    description: 'Learn ethical hacking from scratch. Master Kali Linux, Burp Suite, Metasploit.',
    price: 2299.00, discount_price: 449.00,
    author: 'Deepak Singh',
    category_name: 'Cybersecurity', category_slug: 'cybersecurity',
    difficulty: 'intermediate', duration_hours: 44.0, lessons_count: 365,
    rating: 4.82, reviews_count: 6400, students_count: 25600,
    is_featured: false, is_bestseller: true,
    tags: ['hacking', 'security', 'kali', 'pentesting'],
  },
  {
    id: '6', slug: 'figma-production-design-system',
    title: 'Figma to Production Design System',
    short_description: 'Build scalable design systems from concept to production',
    description: 'Create enterprise-grade design systems in Figma.',
    price: 1499.00, discount_price: 299.00,
    author: 'Meera Patel',
    category_name: 'UI/UX Design', category_slug: 'ui-ux-design',
    difficulty: 'intermediate', duration_hours: 28.0, lessons_count: 210,
    rating: 4.68, reviews_count: 4200, students_count: 18700,
    is_featured: false, is_bestseller: false,
    tags: ['figma', 'design-system', 'ui', 'ux'],
  },
  {
    id: '7', slug: 'go-programming-zero-to-hero',
    title: 'Go Programming - Zero to Hero',
    short_description: 'Learn Go programming and build production-ready microservices',
    description: 'Master Go from fundamentals to advanced concepts. Build REST APIs, microservices.',
    price: 1699.00, discount_price: 349.00,
    author: 'Vikram Rathore',
    category_name: 'Programming Languages', category_slug: 'programming-languages',
    difficulty: 'beginner', duration_hours: 35.0, lessons_count: 280,
    rating: 4.75, reviews_count: 5100, students_count: 21300,
    is_featured: false, is_bestseller: false,
    tags: ['golang', 'microservices', 'backend', 'concurrency'],
  },
  {
    id: '8', slug: 'postgresql-mastery',
    title: 'PostgreSQL Mastery',
    short_description: 'Become a PostgreSQL expert with advanced DBA skills',
    description: 'Complete PostgreSQL course from basics to advanced.',
    price: 1599.00, discount_price: 329.00,
    author: 'Suresh Babu',
    category_name: 'Database Management', category_slug: 'database-management',
    difficulty: 'advanced', duration_hours: 32.0, lessons_count: 245,
    rating: 4.80, reviews_count: 3800, students_count: 15600,
    is_featured: false, is_bestseller: false,
    tags: ['postgresql', 'sql', 'database', 'dba'],
  },
  {
    id: '9', slug: 'fullstack-typescript-nodejs',
    title: 'Full-Stack TypeScript with Node.js',
    short_description: 'Build type-safe full-stack applications with TypeScript',
    description: 'Build end-to-end TypeScript applications. Master Express, Prisma ORM.',
    price: 2199.00, discount_price: 449.00,
    author: 'Sai Srinivas Padala',
    category_name: 'Web Development', category_slug: 'web-development',
    difficulty: 'intermediate', duration_hours: 40.0, lessons_count: 340,
    rating: 4.88, reviews_count: 8900, students_count: 35600,
    is_featured: true, is_bestseller: true,
    tags: ['typescript', 'nodejs', 'express', 'prisma'],
  },
  {
    id: '10', slug: 'kubernetes-docker-complete-guide',
    title: 'Kubernetes & Docker Complete Guide',
    short_description: 'Deploy and manage containerized applications at scale',
    description: 'Master containerization with Docker and orchestration with Kubernetes.',
    price: 2499.00, discount_price: 499.00,
    author: 'Anil Kumar',
    category_name: 'Cloud & DevOps', category_slug: 'cloud-devops',
    difficulty: 'advanced', duration_hours: 46.0, lessons_count: 375,
    rating: 4.86, reviews_count: 7100, students_count: 29800,
    is_featured: true, is_bestseller: false,
    tags: ['kubernetes', 'docker', 'containers', 'devops'],
  },
  {
    id: '11', slug: 'flutter-dart-complete-course',
    title: 'Flutter & Dart - The Complete Course',
    short_description: 'Create stunning cross-platform apps with Flutter and Dart',
    description: 'Build beautiful, natively compiled mobile apps with Flutter.',
    price: 1899.00, discount_price: 379.00,
    author: 'Rahul Verma',
    category_name: 'Mobile Development', category_slug: 'mobile-development',
    difficulty: 'beginner', duration_hours: 44.0, lessons_count: 350,
    rating: 4.74, reviews_count: 6800, students_count: 27500,
    is_featured: false, is_bestseller: true,
    tags: ['flutter', 'dart', 'mobile', 'firebase'],
  },
  {
    id: '12', slug: 'deep-learning-pytorch',
    title: 'Deep Learning with PyTorch',
    short_description: 'Master neural networks and deep learning with PyTorch',
    description: 'Advanced deep learning with PyTorch. Cover CNNs, RNNs, GANs, Transformers.',
    price: 2699.00, discount_price: 549.00,
    author: 'Priya Sharma',
    category_name: 'Data Science', category_slug: 'data-science',
    difficulty: 'advanced', duration_hours: 52.0, lessons_count: 410,
    rating: 4.92, reviews_count: 4500, students_count: 19200,
    is_featured: true, is_bestseller: false,
    tags: ['pytorch', 'deep-learning', 'neural-networks', 'ai'],
  },
];

export const fallbackCategories = [
  { id: '1', name: 'Web Development', slug: 'web-development', icon: '🌐', description: 'Master modern web technologies', course_count: 3 },
  { id: '2', name: 'Data Science', slug: 'data-science', icon: '📊', description: 'Learn data analysis and ML', course_count: 2 },
  { id: '3', name: 'Mobile Development', slug: 'mobile-development', icon: '📱', description: 'Build native and cross-platform apps', course_count: 2 },
  { id: '4', name: 'Cloud & DevOps', slug: 'cloud-devops', icon: '☁️', description: 'Master cloud infrastructure', course_count: 2 },
  { id: '5', name: 'Cybersecurity', slug: 'cybersecurity', icon: '🔒', description: 'Learn ethical hacking and security', course_count: 1 },
  { id: '6', name: 'UI/UX Design', slug: 'ui-ux-design', icon: '🎨', description: 'Create stunning user interfaces', course_count: 1 },
  { id: '7', name: 'Programming Languages', slug: 'programming-languages', icon: '💻', description: 'Deep dive into languages', course_count: 1 },
  { id: '8', name: 'Database Management', slug: 'database-management', icon: '🗄️', description: 'SQL, NoSQL, and more', course_count: 1 },
];
